# Generated by Django 5.0.3 on 2024-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                ("description", models.TextField()),
                ("salary_from", models.CharField(max_length=125)),
                ("salary_to", models.CharField(max_length=125)),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
