# Generated by Django 5.0.3 on 2024-03-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sport", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="date",
        ),
        migrations.DeleteModel(
            name="Date",
        ),
    ]
